### ISSUE TITLE
Jump to poem gracefully

### ISSUE THREAD

**Issue by barelief** [barelief/Pasaulis-Telpa-Akiratin#3]
### Tasks:
- [ ] Implement smooth scrolling to the selected poem
- [ ] Adjust offset so the poem appears below the navbar
- [ ] Unfold poem automatically after scroll
